<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Seed the locations table with Italian CAP data.
     * Contains major cities and comuni across all provinces.
     */
    public function run(): void
    {
        $locations = [
            // ABRUZZO
            ['postal_code' => '67100', 'place_name' => "L'Aquila", 'province' => 'AQ'],
            ['postal_code' => '66100', 'place_name' => 'Chieti', 'province' => 'CH'],
            ['postal_code' => '65100', 'place_name' => 'Pescara', 'province' => 'PE'],
            ['postal_code' => '64100', 'place_name' => 'Teramo', 'province' => 'TE'],
            ['postal_code' => '65121', 'place_name' => 'Pescara', 'province' => 'PE'],
            ['postal_code' => '65122', 'place_name' => 'Pescara', 'province' => 'PE'],
            ['postal_code' => '65123', 'place_name' => 'Pescara', 'province' => 'PE'],
            ['postal_code' => '65124', 'place_name' => 'Pescara', 'province' => 'PE'],
            ['postal_code' => '65125', 'place_name' => 'Pescara', 'province' => 'PE'],
            ['postal_code' => '65126', 'place_name' => 'Pescara', 'province' => 'PE'],
            ['postal_code' => '65127', 'place_name' => 'Pescara', 'province' => 'PE'],
            ['postal_code' => '65128', 'place_name' => 'Pescara', 'province' => 'PE'],
            ['postal_code' => '65129', 'place_name' => 'Pescara', 'province' => 'PE'],
            ['postal_code' => '66034', 'place_name' => 'Lanciano', 'province' => 'CH'],
            ['postal_code' => '66054', 'place_name' => 'Vasto', 'province' => 'CH'],
            ['postal_code' => '67051', 'place_name' => 'Avezzano', 'province' => 'AQ'],
            ['postal_code' => '67039', 'place_name' => 'Sulmona', 'province' => 'AQ'],

            // BASILICATA
            ['postal_code' => '85100', 'place_name' => 'Potenza', 'province' => 'PZ'],
            ['postal_code' => '75100', 'place_name' => 'Matera', 'province' => 'MT'],

            // CALABRIA
            ['postal_code' => '87100', 'place_name' => 'Cosenza', 'province' => 'CS'],
            ['postal_code' => '88100', 'place_name' => 'Catanzaro', 'province' => 'CZ'],
            ['postal_code' => '89100', 'place_name' => 'Reggio Calabria', 'province' => 'RC'],
            ['postal_code' => '88900', 'place_name' => 'Crotone', 'province' => 'KR'],
            ['postal_code' => '89900', 'place_name' => 'Vibo Valentia', 'province' => 'VV'],

            // CAMPANIA
            ['postal_code' => '80100', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80121', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80122', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80123', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80124', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80125', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80126', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80127', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80128', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80129', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80131', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80132', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80133', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80134', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80135', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80136', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80137', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80138', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80139', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80141', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80142', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80143', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80144', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80145', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '80146', 'place_name' => 'Napoli', 'province' => 'NA'],
            ['postal_code' => '84100', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84121', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84122', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84123', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84124', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84125', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84126', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84127', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84128', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84129', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84131', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84132', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84133', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84134', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '84135', 'place_name' => 'Salerno', 'province' => 'SA'],
            ['postal_code' => '82100', 'place_name' => 'Benevento', 'province' => 'BN'],
            ['postal_code' => '83100', 'place_name' => 'Avellino', 'province' => 'AV'],
            ['postal_code' => '81100', 'place_name' => 'Caserta', 'province' => 'CE'],
            ['postal_code' => '80059', 'place_name' => 'Torre del Greco', 'province' => 'NA'],
            ['postal_code' => '80053', 'place_name' => 'Castellammare di Stabia', 'province' => 'NA'],
            ['postal_code' => '80055', 'place_name' => 'Portici', 'province' => 'NA'],
            ['postal_code' => '80044', 'place_name' => 'Ottaviano', 'province' => 'NA'],
            ['postal_code' => '80014', 'place_name' => 'Giugliano in Campania', 'province' => 'NA'],
            ['postal_code' => '80078', 'place_name' => 'Pozzuoli', 'province' => 'NA'],

            // EMILIA-ROMAGNA
            ['postal_code' => '40100', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40121', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40122', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40123', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40124', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40125', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40126', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40127', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40128', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40129', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40131', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40132', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40133', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40134', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40135', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40136', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40137', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40138', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40139', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '40141', 'place_name' => 'Bologna', 'province' => 'BO'],
            ['postal_code' => '43100', 'place_name' => 'Parma', 'province' => 'PR'],
            ['postal_code' => '43121', 'place_name' => 'Parma', 'province' => 'PR'],
            ['postal_code' => '43122', 'place_name' => 'Parma', 'province' => 'PR'],
            ['postal_code' => '43123', 'place_name' => 'Parma', 'province' => 'PR'],
            ['postal_code' => '43124', 'place_name' => 'Parma', 'province' => 'PR'],
            ['postal_code' => '43125', 'place_name' => 'Parma', 'province' => 'PR'],
            ['postal_code' => '43126', 'place_name' => 'Parma', 'province' => 'PR'],
            ['postal_code' => '42100', 'place_name' => 'Reggio Emilia', 'province' => 'RE'],
            ['postal_code' => '42121', 'place_name' => 'Reggio Emilia', 'province' => 'RE'],
            ['postal_code' => '42122', 'place_name' => 'Reggio Emilia', 'province' => 'RE'],
            ['postal_code' => '42123', 'place_name' => 'Reggio Emilia', 'province' => 'RE'],
            ['postal_code' => '42124', 'place_name' => 'Reggio Emilia', 'province' => 'RE'],
            ['postal_code' => '42125', 'place_name' => 'Reggio Emilia', 'province' => 'RE'],
            ['postal_code' => '41100', 'place_name' => 'Modena', 'province' => 'MO'],
            ['postal_code' => '41121', 'place_name' => 'Modena', 'province' => 'MO'],
            ['postal_code' => '41122', 'place_name' => 'Modena', 'province' => 'MO'],
            ['postal_code' => '41123', 'place_name' => 'Modena', 'province' => 'MO'],
            ['postal_code' => '41124', 'place_name' => 'Modena', 'province' => 'MO'],
            ['postal_code' => '41125', 'place_name' => 'Modena', 'province' => 'MO'],
            ['postal_code' => '41126', 'place_name' => 'Modena', 'province' => 'MO'],
            ['postal_code' => '44100', 'place_name' => 'Ferrara', 'province' => 'FE'],
            ['postal_code' => '44121', 'place_name' => 'Ferrara', 'province' => 'FE'],
            ['postal_code' => '44122', 'place_name' => 'Ferrara', 'province' => 'FE'],
            ['postal_code' => '44123', 'place_name' => 'Ferrara', 'province' => 'FE'],
            ['postal_code' => '44124', 'place_name' => 'Ferrara', 'province' => 'FE'],
            ['postal_code' => '47921', 'place_name' => 'Rimini', 'province' => 'RN'],
            ['postal_code' => '47922', 'place_name' => 'Rimini', 'province' => 'RN'],
            ['postal_code' => '47923', 'place_name' => 'Rimini', 'province' => 'RN'],
            ['postal_code' => '47924', 'place_name' => 'Rimini', 'province' => 'RN'],
            ['postal_code' => '47521', 'place_name' => 'Cesena', 'province' => 'FC'],
            ['postal_code' => '47522', 'place_name' => 'Cesena', 'province' => 'FC'],
            ['postal_code' => '47023', 'place_name' => 'Cesena', 'province' => 'FC'],
            ['postal_code' => '47121', 'place_name' => 'Forli', 'province' => 'FC'],
            ['postal_code' => '47122', 'place_name' => 'Forli', 'province' => 'FC'],
            ['postal_code' => '29100', 'place_name' => 'Piacenza', 'province' => 'PC'],
            ['postal_code' => '29121', 'place_name' => 'Piacenza', 'province' => 'PC'],
            ['postal_code' => '29122', 'place_name' => 'Piacenza', 'province' => 'PC'],
            ['postal_code' => '48121', 'place_name' => 'Ravenna', 'province' => 'RA'],
            ['postal_code' => '48122', 'place_name' => 'Ravenna', 'province' => 'RA'],
            ['postal_code' => '48123', 'place_name' => 'Ravenna', 'province' => 'RA'],
            ['postal_code' => '48124', 'place_name' => 'Ravenna', 'province' => 'RA'],
            ['postal_code' => '40026', 'place_name' => 'Imola', 'province' => 'BO'],
            ['postal_code' => '41049', 'place_name' => 'Sassuolo', 'province' => 'MO'],
            ['postal_code' => '41012', 'place_name' => 'Carpi', 'province' => 'MO'],

            // FRIULI VENEZIA GIULIA
            ['postal_code' => '34100', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34121', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34122', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34123', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34124', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34125', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34126', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34127', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34128', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34129', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34131', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34132', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34133', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34134', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34135', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34136', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34137', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34138', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34139', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34141', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34142', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34143', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34144', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34145', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34146', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34147', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34148', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34149', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '34151', 'place_name' => 'Trieste', 'province' => 'TS'],
            ['postal_code' => '33100', 'place_name' => 'Udine', 'province' => 'UD'],
            ['postal_code' => '34170', 'place_name' => 'Gorizia', 'province' => 'GO'],
            ['postal_code' => '33170', 'place_name' => 'Pordenone', 'province' => 'PN'],

            // LAZIO
            ['postal_code' => '00100', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00118', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00119', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00120', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00121', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00122', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00123', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00124', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00125', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00126', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00127', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00128', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00131', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00132', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00133', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00134', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00135', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00136', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00137', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00138', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00139', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00141', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00142', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00143', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00144', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00145', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00146', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00147', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00148', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00149', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00151', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00152', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00153', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00154', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00155', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00156', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00157', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00158', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00159', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00161', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00162', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00163', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00164', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00165', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00166', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00167', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00168', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00169', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00171', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00172', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00173', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00174', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00175', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00176', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00177', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00178', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00179', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00181', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00182', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00183', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00184', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00185', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00186', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00187', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00188', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00189', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00191', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00192', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00193', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00194', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00195', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00196', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00197', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00198', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '00199', 'place_name' => 'Roma', 'province' => 'RM'],
            ['postal_code' => '03100', 'place_name' => 'Frosinone', 'province' => 'FR'],
            ['postal_code' => '04100', 'place_name' => 'Latina', 'province' => 'LT'],
            ['postal_code' => '02100', 'place_name' => 'Rieti', 'province' => 'RI'],
            ['postal_code' => '01100', 'place_name' => 'Viterbo', 'province' => 'VT'],
            ['postal_code' => '00015', 'place_name' => 'Monterotondo', 'province' => 'RM'],
            ['postal_code' => '00040', 'place_name' => 'Pomezia', 'province' => 'RM'],
            ['postal_code' => '00048', 'place_name' => 'Nettuno', 'province' => 'RM'],
            ['postal_code' => '00041', 'place_name' => 'Albano Laziale', 'province' => 'RM'],
            ['postal_code' => '00044', 'place_name' => 'Frascati', 'province' => 'RM'],
            ['postal_code' => '00053', 'place_name' => 'Civitavecchia', 'province' => 'RM'],
            ['postal_code' => '00019', 'place_name' => 'Tivoli', 'province' => 'RM'],
            ['postal_code' => '00054', 'place_name' => 'Fiumicino', 'province' => 'RM'],
            ['postal_code' => '00058', 'place_name' => 'Santa Marinella', 'province' => 'RM'],

            // LIGURIA
            ['postal_code' => '16100', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16121', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16122', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16123', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16124', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16125', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16126', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16127', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16128', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16129', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16131', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16132', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16133', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16134', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16135', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16136', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16137', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16138', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16139', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16141', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16142', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16143', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16144', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16145', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16146', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16147', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16148', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16149', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16151', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16152', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16153', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16154', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16155', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16156', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16157', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16158', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16159', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16161', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16162', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16163', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16164', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16165', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16166', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '16167', 'place_name' => 'Genova', 'province' => 'GE'],
            ['postal_code' => '19100', 'place_name' => 'La Spezia', 'province' => 'SP'],
            ['postal_code' => '17100', 'place_name' => 'Savona', 'province' => 'SV'],
            ['postal_code' => '18100', 'place_name' => 'Imperia', 'province' => 'IM'],
            ['postal_code' => '18038', 'place_name' => 'Sanremo', 'province' => 'IM'],

            // LOMBARDIA
            ['postal_code' => '20100', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20121', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20122', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20123', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20124', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20125', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20126', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20127', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20128', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20129', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20131', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20132', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20133', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20134', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20135', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20136', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20137', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20138', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20139', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20141', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20142', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20143', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20144', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20145', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20146', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20147', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20148', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20149', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20151', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20152', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20153', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20154', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20155', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20156', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20157', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20158', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20159', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20161', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '20162', 'place_name' => 'Milano', 'province' => 'MI'],
            ['postal_code' => '25100', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25121', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25122', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25123', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25124', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25125', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25126', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25127', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25128', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25129', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25131', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25132', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25133', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25134', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25135', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '25136', 'place_name' => 'Brescia', 'province' => 'BS'],
            ['postal_code' => '24100', 'place_name' => 'Bergamo', 'province' => 'BG'],
            ['postal_code' => '24121', 'place_name' => 'Bergamo', 'province' => 'BG'],
            ['postal_code' => '24122', 'place_name' => 'Bergamo', 'province' => 'BG'],
            ['postal_code' => '24123', 'place_name' => 'Bergamo', 'province' => 'BG'],
            ['postal_code' => '24124', 'place_name' => 'Bergamo', 'province' => 'BG'],
            ['postal_code' => '24125', 'place_name' => 'Bergamo', 'province' => 'BG'],
            ['postal_code' => '24126', 'place_name' => 'Bergamo', 'province' => 'BG'],
            ['postal_code' => '24127', 'place_name' => 'Bergamo', 'province' => 'BG'],
            ['postal_code' => '24128', 'place_name' => 'Bergamo', 'province' => 'BG'],
            ['postal_code' => '24129', 'place_name' => 'Bergamo', 'province' => 'BG'],
            ['postal_code' => '20900', 'place_name' => 'Monza', 'province' => 'MB'],
            ['postal_code' => '27100', 'place_name' => 'Pavia', 'province' => 'PV'],
            ['postal_code' => '21100', 'place_name' => 'Varese', 'province' => 'VA'],
            ['postal_code' => '22100', 'place_name' => 'Como', 'province' => 'CO'],
            ['postal_code' => '23900', 'place_name' => 'Lecco', 'province' => 'LC'],
            ['postal_code' => '46100', 'place_name' => 'Mantova', 'province' => 'MN'],
            ['postal_code' => '26100', 'place_name' => 'Cremona', 'province' => 'CR'],
            ['postal_code' => '23100', 'place_name' => 'Sondrio', 'province' => 'SO'],
            ['postal_code' => '26900', 'place_name' => 'Lodi', 'province' => 'LO'],
            ['postal_code' => '20099', 'place_name' => 'Sesto San Giovanni', 'province' => 'MI'],
            ['postal_code' => '20092', 'place_name' => 'Cinisello Balsamo', 'province' => 'MI'],
            ['postal_code' => '20052', 'place_name' => 'Monza', 'province' => 'MB'],

            // MARCHE
            ['postal_code' => '60100', 'place_name' => 'Ancona', 'province' => 'AN'],
            ['postal_code' => '60121', 'place_name' => 'Ancona', 'province' => 'AN'],
            ['postal_code' => '60122', 'place_name' => 'Ancona', 'province' => 'AN'],
            ['postal_code' => '60123', 'place_name' => 'Ancona', 'province' => 'AN'],
            ['postal_code' => '60124', 'place_name' => 'Ancona', 'province' => 'AN'],
            ['postal_code' => '60125', 'place_name' => 'Ancona', 'province' => 'AN'],
            ['postal_code' => '60126', 'place_name' => 'Ancona', 'province' => 'AN'],
            ['postal_code' => '60127', 'place_name' => 'Ancona', 'province' => 'AN'],
            ['postal_code' => '60128', 'place_name' => 'Ancona', 'province' => 'AN'],
            ['postal_code' => '60129', 'place_name' => 'Ancona', 'province' => 'AN'],
            ['postal_code' => '60131', 'place_name' => 'Ancona', 'province' => 'AN'],
            ['postal_code' => '61121', 'place_name' => 'Pesaro', 'province' => 'PU'],
            ['postal_code' => '61122', 'place_name' => 'Pesaro', 'province' => 'PU'],
            ['postal_code' => '63100', 'place_name' => 'Ascoli Piceno', 'province' => 'AP'],
            ['postal_code' => '63900', 'place_name' => 'Fermo', 'province' => 'FM'],
            ['postal_code' => '62100', 'place_name' => 'Macerata', 'province' => 'MC'],

            // MOLISE
            ['postal_code' => '86100', 'place_name' => 'Campobasso', 'province' => 'CB'],
            ['postal_code' => '86170', 'place_name' => 'Isernia', 'province' => 'IS'],

            // PIEMONTE
            ['postal_code' => '10100', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10121', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10122', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10123', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10124', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10125', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10126', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10127', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10128', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10129', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10131', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10132', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10133', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10134', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10135', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10136', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10137', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10138', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10139', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10141', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10142', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10143', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10144', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10145', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10146', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10147', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10148', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10149', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10151', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10152', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10153', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10154', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10155', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '10156', 'place_name' => 'Torino', 'province' => 'TO'],
            ['postal_code' => '15121', 'place_name' => 'Alessandria', 'province' => 'AL'],
            ['postal_code' => '15122', 'place_name' => 'Alessandria', 'province' => 'AL'],
            ['postal_code' => '14100', 'place_name' => 'Asti', 'province' => 'AT'],
            ['postal_code' => '13900', 'place_name' => 'Biella', 'province' => 'BI'],
            ['postal_code' => '12100', 'place_name' => 'Cuneo', 'province' => 'CN'],
            ['postal_code' => '28100', 'place_name' => 'Novara', 'province' => 'NO'],
            ['postal_code' => '28922', 'place_name' => 'Verbania', 'province' => 'VB'],
            ['postal_code' => '13100', 'place_name' => 'Vercelli', 'province' => 'VC'],

            // PUGLIA
            ['postal_code' => '70100', 'place_name' => 'Bari', 'province' => 'BA'],
            ['postal_code' => '70121', 'place_name' => 'Bari', 'province' => 'BA'],
            ['postal_code' => '70122', 'place_name' => 'Bari', 'province' => 'BA'],
            ['postal_code' => '70123', 'place_name' => 'Bari', 'province' => 'BA'],
            ['postal_code' => '70124', 'place_name' => 'Bari', 'province' => 'BA'],
            ['postal_code' => '70125', 'place_name' => 'Bari', 'province' => 'BA'],
            ['postal_code' => '70126', 'place_name' => 'Bari', 'province' => 'BA'],
            ['postal_code' => '70127', 'place_name' => 'Bari', 'province' => 'BA'],
            ['postal_code' => '70128', 'place_name' => 'Bari', 'province' => 'BA'],
            ['postal_code' => '70129', 'place_name' => 'Bari', 'province' => 'BA'],
            ['postal_code' => '70131', 'place_name' => 'Bari', 'province' => 'BA'],
            ['postal_code' => '70132', 'place_name' => 'Bari', 'province' => 'BA'],
            ['postal_code' => '73100', 'place_name' => 'Lecce', 'province' => 'LE'],
            ['postal_code' => '74121', 'place_name' => 'Taranto', 'province' => 'TA'],
            ['postal_code' => '74122', 'place_name' => 'Taranto', 'province' => 'TA'],
            ['postal_code' => '74123', 'place_name' => 'Taranto', 'province' => 'TA'],
            ['postal_code' => '71121', 'place_name' => 'Foggia', 'province' => 'FG'],
            ['postal_code' => '71122', 'place_name' => 'Foggia', 'province' => 'FG'],
            ['postal_code' => '76121', 'place_name' => 'Barletta', 'province' => 'BT'],
            ['postal_code' => '76123', 'place_name' => 'Andria', 'province' => 'BT'],
            ['postal_code' => '76125', 'place_name' => 'Trani', 'province' => 'BT'],
            ['postal_code' => '72100', 'place_name' => 'Brindisi', 'province' => 'BR'],

            // SARDEGNA
            ['postal_code' => '09100', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '09121', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '09122', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '09123', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '09124', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '09125', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '09126', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '09127', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '09128', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '09129', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '09131', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '09132', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '09133', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '09134', 'place_name' => 'Cagliari', 'province' => 'CA'],
            ['postal_code' => '07100', 'place_name' => 'Sassari', 'province' => 'SS'],
            ['postal_code' => '08100', 'place_name' => 'Nuoro', 'province' => 'NU'],
            ['postal_code' => '09170', 'place_name' => 'Oristano', 'province' => 'OR'],
            ['postal_code' => '09013', 'place_name' => 'Carbonia', 'province' => 'SU'],
            ['postal_code' => '09016', 'place_name' => 'Iglesias', 'province' => 'SU'],
            ['postal_code' => '07026', 'place_name' => 'Olbia', 'province' => 'SS'],
            ['postal_code' => '07041', 'place_name' => 'Alghero', 'province' => 'SS'],

            // SICILIA
            ['postal_code' => '90100', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90121', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90122', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90123', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90124', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90125', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90126', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90127', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90128', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90129', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90131', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90132', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90133', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90134', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90135', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90136', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90137', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90138', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90139', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90141', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90142', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90143', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90144', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90145', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90146', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90147', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90148', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90149', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '90151', 'place_name' => 'Palermo', 'province' => 'PA'],
            ['postal_code' => '95100', 'place_name' => 'Catania', 'province' => 'CT'],
            ['postal_code' => '95121', 'place_name' => 'Catania', 'province' => 'CT'],
            ['postal_code' => '95122', 'place_name' => 'Catania', 'province' => 'CT'],
            ['postal_code' => '95123', 'place_name' => 'Catania', 'province' => 'CT'],
            ['postal_code' => '95124', 'place_name' => 'Catania', 'province' => 'CT'],
            ['postal_code' => '95125', 'place_name' => 'Catania', 'province' => 'CT'],
            ['postal_code' => '95126', 'place_name' => 'Catania', 'province' => 'CT'],
            ['postal_code' => '95127', 'place_name' => 'Catania', 'province' => 'CT'],
            ['postal_code' => '95128', 'place_name' => 'Catania', 'province' => 'CT'],
            ['postal_code' => '95129', 'place_name' => 'Catania', 'province' => 'CT'],
            ['postal_code' => '95131', 'place_name' => 'Catania', 'province' => 'CT'],
            ['postal_code' => '96100', 'place_name' => 'Siracusa', 'province' => 'SR'],
            ['postal_code' => '98100', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98121', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98122', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98123', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98124', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98125', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98126', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98127', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98128', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98129', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98131', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98132', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98133', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98134', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98135', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98136', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98137', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98138', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98139', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98141', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98142', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98143', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98144', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98145', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98146', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98147', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98148', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98149', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98151', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98152', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98153', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98154', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98155', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98156', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98157', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98158', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98159', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98161', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98162', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98163', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98164', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98165', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98166', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98167', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '98168', 'place_name' => 'Messina', 'province' => 'ME'],
            ['postal_code' => '93100', 'place_name' => 'Caltanissetta', 'province' => 'CL'],
            ['postal_code' => '92100', 'place_name' => 'Agrigento', 'province' => 'AG'],
            ['postal_code' => '94100', 'place_name' => 'Enna', 'province' => 'EN'],
            ['postal_code' => '97100', 'place_name' => 'Ragusa', 'province' => 'RG'],
            ['postal_code' => '91100', 'place_name' => 'Trapani', 'province' => 'TP'],

            // TOSCANA
            ['postal_code' => '50100', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50121', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50122', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50123', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50124', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50125', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50126', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50127', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50128', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50129', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50131', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50132', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50133', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50134', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50135', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50136', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50137', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50138', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50139', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50141', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50142', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50143', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50144', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '50145', 'place_name' => 'Firenze', 'province' => 'FI'],
            ['postal_code' => '56100', 'place_name' => 'Pisa', 'province' => 'PI'],
            ['postal_code' => '56121', 'place_name' => 'Pisa', 'province' => 'PI'],
            ['postal_code' => '56122', 'place_name' => 'Pisa', 'province' => 'PI'],
            ['postal_code' => '56123', 'place_name' => 'Pisa', 'province' => 'PI'],
            ['postal_code' => '56124', 'place_name' => 'Pisa', 'province' => 'PI'],
            ['postal_code' => '56125', 'place_name' => 'Pisa', 'province' => 'PI'],
            ['postal_code' => '56126', 'place_name' => 'Pisa', 'province' => 'PI'],
            ['postal_code' => '56127', 'place_name' => 'Pisa', 'province' => 'PI'],
            ['postal_code' => '56128', 'place_name' => 'Pisa', 'province' => 'PI'],
            ['postal_code' => '53100', 'place_name' => 'Siena', 'province' => 'SI'],
            ['postal_code' => '57100', 'place_name' => 'Livorno', 'province' => 'LI'],
            ['postal_code' => '57121', 'place_name' => 'Livorno', 'province' => 'LI'],
            ['postal_code' => '57122', 'place_name' => 'Livorno', 'province' => 'LI'],
            ['postal_code' => '57123', 'place_name' => 'Livorno', 'province' => 'LI'],
            ['postal_code' => '57124', 'place_name' => 'Livorno', 'province' => 'LI'],
            ['postal_code' => '57125', 'place_name' => 'Livorno', 'province' => 'LI'],
            ['postal_code' => '57126', 'place_name' => 'Livorno', 'province' => 'LI'],
            ['postal_code' => '57127', 'place_name' => 'Livorno', 'province' => 'LI'],
            ['postal_code' => '57128', 'place_name' => 'Livorno', 'province' => 'LI'],
            ['postal_code' => '52100', 'place_name' => 'Arezzo', 'province' => 'AR'],
            ['postal_code' => '51100', 'place_name' => 'Pistoia', 'province' => 'PT'],
            ['postal_code' => '55100', 'place_name' => 'Lucca', 'province' => 'LU'],
            ['postal_code' => '58100', 'place_name' => 'Grosseto', 'province' => 'GR'],
            ['postal_code' => '54100', 'place_name' => 'Massa', 'province' => 'MS'],
            ['postal_code' => '59100', 'place_name' => 'Prato', 'province' => 'PO'],

            // TRENTINO-ALTO ADIGE
            ['postal_code' => '38100', 'place_name' => 'Trento', 'province' => 'TN'],
            ['postal_code' => '38121', 'place_name' => 'Trento', 'province' => 'TN'],
            ['postal_code' => '38122', 'place_name' => 'Trento', 'province' => 'TN'],
            ['postal_code' => '38123', 'place_name' => 'Trento', 'province' => 'TN'],
            ['postal_code' => '39100', 'place_name' => 'Bolzano', 'province' => 'BZ'],

            // UMBRIA
            ['postal_code' => '06100', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '06121', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '06122', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '06123', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '06124', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '06125', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '06126', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '06127', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '06128', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '06129', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '06131', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '06132', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '06134', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '06135', 'place_name' => 'Perugia', 'province' => 'PG'],
            ['postal_code' => '05100', 'place_name' => 'Terni', 'province' => 'TR'],

            // VALLE D'AOSTA
            ['postal_code' => '11100', 'place_name' => 'Aosta', 'province' => 'AO'],

            // VENETO
            ['postal_code' => '30100', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30121', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30122', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30123', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30124', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30125', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30126', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30131', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30132', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30133', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30135', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30141', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30142', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30170', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30171', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30172', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30173', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30174', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30175', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '30176', 'place_name' => 'Venezia', 'province' => 'VE'],
            ['postal_code' => '35100', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35121', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35122', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35123', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35124', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35125', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35126', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35127', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35128', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35129', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35131', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35132', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35133', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35134', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35135', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35136', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35137', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35138', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35139', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35141', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35142', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '35143', 'place_name' => 'Padova', 'province' => 'PD'],
            ['postal_code' => '37100', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37121', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37122', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37123', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37124', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37125', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37126', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37127', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37128', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37129', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37131', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37132', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37133', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37134', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37135', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37136', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37137', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37138', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37139', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37141', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '37142', 'place_name' => 'Verona', 'province' => 'VR'],
            ['postal_code' => '36100', 'place_name' => 'Vicenza', 'province' => 'VI'],
            ['postal_code' => '31100', 'place_name' => 'Treviso', 'province' => 'TV'],
            ['postal_code' => '45100', 'place_name' => 'Rovigo', 'province' => 'RO'],
            ['postal_code' => '32100', 'place_name' => 'Belluno', 'province' => 'BL'],
        ];

        // Insert in chunks of 100
        foreach (array_chunk($locations, 100) as $chunk) {
            Location::insert($chunk);
        }
    }
}
