<?php

/**
 * Mapping filiali BRT: codice filiale → CAP di riferimento.
 * Usato per determinare automaticamente il departureDepot partendo dal CAP del mittente.
 * Fonte: tabella ufficiale BRT (Filiale / Codice / CAP).
 *
 * Strategia lookup in BrtService::resolveFilialeByCap():
 *   1. Match esatto sul CAP
 *   2. Match sulle prime 3 cifre (stesso sottozone postale)
 *   3. Match sulle prime 2 cifre (stessa provincia)
 *   4. Fallback al depot configurato in BRT_DEPARTURE_DEPOT
 */
return [
    'filiali' => [
        ['codice' => 38,  'nome' => 'AGRIGENTO',           'cap' => '92021'],
        ['codice' => 39,  'nome' => 'ALESSANDRIA',          'cap' => '15072'],
        ['codice' => 66,  'nome' => 'ANCONA',               'cap' => '60027'],
        ['codice' => 146, 'nome' => 'ANCONA CENTRO',        'cap' => '60131'],
        ['codice' => 136, 'nome' => 'AOSTA',                'cap' => '11020'],
        ['codice' => 79,  'nome' => 'AREZZO',               'cap' => '52041'],
        ['codice' => 76,  'nome' => 'ASTI',                 'cap' => '14033'],
        ['codice' => 154, 'nome' => 'ATENA LUCANA',         'cap' => '84030'],
        ['codice' => 75,  'nome' => 'AVELLINO',             'cap' => '83020'],
        ['codice' => 7,   'nome' => 'BARI',                 'cap' => '70123'],
        ['codice' => 221, 'nome' => 'BARI MESSAGGERIA',     'cap' => '70026'],
        ['codice' => 161, 'nome' => 'BARI SUD',             'cap' => '70026'],
        ['codice' => 61,  'nome' => 'BASSANO',              'cap' => '36061'],
        ['codice' => 16,  'nome' => 'BELLUNO',              'cap' => '32100'],
        ['codice' => 116, 'nome' => 'BERGAMO GRASSOBBIO',   'cap' => '24050'],
        ['codice' => 86,  'nome' => 'BIELLA',               'cap' => '13876'],
        ['codice' => 275, 'nome' => 'BOLOGNA INTERPORTO',   'cap' => '40010'],
        ['codice' => 2,   'nome' => 'BOLOGNA ROVERI 1',     'cap' => '40138'],
        ['codice' => 173, 'nome' => 'BOLOGNA ROVERI 2',     'cap' => '40138'],
        ['codice' => 48,  'nome' => 'BOLZANO',              'cap' => '39100'],
        ['codice' => 106, 'nome' => 'BORGOMANERO',          'cap' => '28010'],
        ['codice' => 45,  'nome' => 'BRA',                  'cap' => '12060'],
        ['codice' => 93,  'nome' => 'BRESCIA',              'cap' => '25046'],
        ['codice' => 173, 'nome' => 'BRESCIA CENTRO',       'cap' => '25125'],
        ['codice' => 107, 'nome' => 'BRESSANONE',           'cap' => '39040'],
        ['codice' => 9,   'nome' => 'BRINDISI',             'cap' => '72100'],
        ['codice' => 27,  'nome' => 'CAGLIARI',             'cap' => '09032'],
        ['codice' => 138, 'nome' => 'CAGLIARI ELMAS',       'cap' => '09067'],
        ['codice' => 183, 'nome' => 'CAGLIARI MESSAGGERIA', 'cap' => '09122'],
        ['codice' => 35,  'nome' => 'CALTANISSETTA',        'cap' => '93100'],
        ['codice' => 57,  'nome' => 'CAMPOBASSO',           'cap' => '86025'],
        ['codice' => 160, 'nome' => 'CASEI GEROLA',         'cap' => '27050'],
        ['codice' => 149, 'nome' => 'CASSINO',              'cap' => '03043'],
        ['codice' => 12,  'nome' => 'CASTELLAMMARE STABIA', 'cap' => '80053'],
        ['codice' => 15,  'nome' => 'CASTROVILLARI',        'cap' => '87012'],
        ['codice' => 144, 'nome' => 'CATANIA CENTRO',       'cap' => '95040'],
        ['codice' => 15,  'nome' => 'CATANZARO',            'cap' => '88044'],
        ['codice' => 134, 'nome' => 'CATTOLICA',            'cap' => '47841'],
        ['codice' => 134, 'nome' => 'CESENA',               'cap' => '47043'],
        ['codice' => 227, 'nome' => 'CESSALTO',             'cap' => '31040'],
        ['codice' => 159, 'nome' => 'CITTA DI CASTELLO',    'cap' => '06016'],
        ['codice' => 62,  'nome' => 'CIVITANOVA MARCHE',    'cap' => '62012'],
        ['codice' => 96,  'nome' => 'COMO',                 'cap' => '22075'],
        ['codice' => 14,  'nome' => 'COSENZA',              'cap' => '87036'],
        ['codice' => 36,  'nome' => 'CREMONA',              'cap' => '26100'],
        ['codice' => 165, 'nome' => 'CRESPELLANO',          'cap' => '40053'],
        ['codice' => 77,  'nome' => 'CUNEO',                'cap' => '12040'],
        ['codice' => 132, 'nome' => 'DESENZANO',            'cap' => '25015'],
        ['codice' => 108, 'nome' => 'EMPOLI',               'cap' => '50053'],
        ['codice' => 163, 'nome' => 'FAENZA',               'cap' => '48018'],
        ['codice' => 224, 'nome' => 'FIRENZE CALENZANO',    'cap' => '50041'],
        ['codice' => 28,  'nome' => 'FIRENZE OSMANNORO',    'cap' => '50019'],
        ['codice' => 229, 'nome' => 'FIRENZE TRE VILLE',    'cap' => '50013'],
        ['codice' => 145, 'nome' => 'FIRENZE VALDARNO',     'cap' => '52028'],
        ['codice' => 8,   'nome' => 'FOGGIA',               'cap' => '71122'],
        ['codice' => 88,  'nome' => 'FOLIGNO',              'cap' => '06036'],
        ['codice' => 25,  'nome' => 'FORLI',                'cap' => '47122'],
        ['codice' => 74,  'nome' => 'FROSINONE',            'cap' => '03013'],
        ['codice' => 176, 'nome' => 'GENOVA BOLZANETO',     'cap' => '16010'],
        ['codice' => 2,   'nome' => 'GENOVA CORNIGLIANO',   'cap' => '16152'],
        ['codice' => 135, 'nome' => 'GENOVA FEGINO',        'cap' => '16161'],
        ['codice' => 116, 'nome' => 'GORIZIA',              'cap' => '34070'],
        ['codice' => 156, 'nome' => 'GRAVELLONA TOCE',      'cap' => '28924'],
        ['codice' => 85,  'nome' => 'GROSSETO',             'cap' => '58100'],
        ['codice' => 142, 'nome' => 'GUIDONIA',             'cap' => '00012'],
        ['codice' => 100, 'nome' => 'IMOLA',                'cap' => '40026'],
        ['codice' => 4,   'nome' => 'IMPERIA',              'cap' => '18010'],
        ['codice' => 21,  'nome' => 'IVREA',                'cap' => '10010'],
        ['codice' => 128, 'nome' => 'JESI',                 'cap' => '60035'],
        ['codice' => 55,  'nome' => 'L\'AQUILA',            'cap' => '67100'],
        ['codice' => 44,  'nome' => 'LA SPEZIA',            'cap' => '19020'],
        ['codice' => 73,  'nome' => 'LATINA',               'cap' => '04100'],
        ['codice' => 11,  'nome' => 'LECCE',                'cap' => '73010'],
        ['codice' => 153, 'nome' => 'LECCE SUD',            'cap' => '73020'],
        ['codice' => 83,  'nome' => 'LECCO',                'cap' => '23848'],
        ['codice' => 184, 'nome' => 'LIVIGNO',              'cap' => '23030'],
        ['codice' => 91,  'nome' => 'LIVORNO',              'cap' => '57014'],
        ['codice' => 111, 'nome' => 'LODI',                 'cap' => '26854'],
        ['codice' => 90,  'nome' => 'LUCCA',                'cap' => '55100'],
        ['codice' => 65,  'nome' => 'MANTOVA',              'cap' => '46030'],
        ['codice' => 37,  'nome' => 'MARSALA',              'cap' => '91025'],
        ['codice' => 167, 'nome' => 'MATERA',               'cap' => '75100'],
        ['codice' => 118, 'nome' => 'MERANO',               'cap' => '39011'],
        ['codice' => 30,  'nome' => 'MESSINA',              'cap' => '98134'],
        ['codice' => 121, 'nome' => 'MI CEVEDALE',          'cap' => '20158'],
        ['codice' => 222, 'nome' => 'MILANO ALBAIRATE',     'cap' => '20080'],
        ['codice' => 89,  'nome' => 'MILANO BOVISA',        'cap' => '20158'],
        ['codice' => 158, 'nome' => 'MILANO BOVISA 2',      'cap' => '20158'],
        ['codice' => 185, 'nome' => 'MILANO BOVISA 3',      'cap' => '20158'],
        ['codice' => 179, 'nome' => 'MILANO CENTRO',        'cap' => '20138'],
        ['codice' => 130, 'nome' => 'MILANO CERTOSA',       'cap' => '20151'],
        ['codice' => 202, 'nome' => 'MILANO CINISELLO',     'cap' => '20092'],
        ['codice' => 166, 'nome' => 'MILANO LANDRIANO',     'cap' => '27015'],
        ['codice' => 249, 'nome' => 'MILANO LISCATE',       'cap' => '20060'],
        ['codice' => 186, 'nome' => 'MILANO LISCATE 2',     'cap' => '20060'],
        ['codice' => 50,  'nome' => 'MILANO SEDRIANO',      'cap' => '20018'],
        ['codice' => 5,   'nome' => 'MILANO SUD',           'cap' => '27015'],
        ['codice' => 18,  'nome' => 'MODENA',               'cap' => '41011'],
        ['codice' => 171, 'nome' => 'MONCALIERI',           'cap' => '10028'],
        ['codice' => 165, 'nome' => 'MONZA',                'cap' => '20863'],
        ['codice' => 164, 'nome' => 'NA-CASANDRINO',        'cap' => '80025'],
        ['codice' => 143, 'nome' => 'NAPOLI CENTRO',        'cap' => '80025'],
        ['codice' => 67,  'nome' => 'NAPOLI MARCIANISE',    'cap' => '81025'],
        ['codice' => 127, 'nome' => 'NAPOLI NOLA',          'cap' => '80035'],
        ['codice' => 280, 'nome' => 'NAPOLI NORD',          'cap' => '81025'],
        ['codice' => 177, 'nome' => 'NAPOLI OVEST',         'cap' => '80025'],
        ['codice' => 56,  'nome' => 'NOVARA',               'cap' => '28060'],
        ['codice' => 113, 'nome' => 'OLBIA',                'cap' => '07026'],
        ['codice' => 161, 'nome' => 'ORIGGIO',              'cap' => '21040'],
        ['codice' => 104, 'nome' => 'ORISTANO',             'cap' => '09096'],
        ['codice' => 139, 'nome' => 'PADOVA EST',           'cap' => '35027'],
        ['codice' => 6,   'nome' => 'PADOVA INTERPORTO',    'cap' => '35127'],
        ['codice' => 214, 'nome' => 'PADOVA MESSAGGERIA',   'cap' => '35127'],
        ['codice' => 32,  'nome' => 'PALERMO CARINI',       'cap' => '90044'],
        ['codice' => 148, 'nome' => 'PALERMO CENTRO',       'cap' => '90120'],
        ['codice' => 20,  'nome' => 'PARMA',                'cap' => '43010'],
        ['codice' => 223, 'nome' => 'PARMA MESSAGGERIA',    'cap' => '43010'],
        ['codice' => 54,  'nome' => 'PAVIA',                'cap' => '27010'],
        ['codice' => 26,  'nome' => 'PERUGIA',              'cap' => '06135'],
        ['codice' => 51,  'nome' => 'PESARO',               'cap' => '61022'],
        ['codice' => 62,  'nome' => 'PESCARA',              'cap' => '66020'],
        ['codice' => 182, 'nome' => 'PESCARA OVEST',        'cap' => '65012'],
        ['codice' => 22,  'nome' => 'PIACENZA',             'cap' => '29012'],
        ['codice' => 220, 'nome' => 'PIEVE EMANUELE',       'cap' => '20072'],
        ['codice' => 162, 'nome' => 'PIOMBINO',             'cap' => '57025'],
        ['codice' => 117, 'nome' => 'PISA CENTRO',          'cap' => '56017'],
        ['codice' => 99,  'nome' => 'PISA LAVORIA',         'cap' => '56040'],
        ['codice' => 92,  'nome' => 'PISTOIA',              'cap' => '51031'],
        ['codice' => 114, 'nome' => 'POMEZIA',              'cap' => '00040'],
        ['codice' => 69,  'nome' => 'PORDENONE',            'cap' => '33080'],
        ['codice' => 53,  'nome' => 'PORTO D\'ASCOLI',      'cap' => '63074'],
        ['codice' => 81,  'nome' => 'PORTO TORRES',         'cap' => '07046'],
        ['codice' => 112, 'nome' => 'PORTOGRUARO',          'cap' => '30026'],
        ['codice' => 13,  'nome' => 'POTENZA',              'cap' => '85050'],
        ['codice' => 84,  'nome' => 'PRATO',                'cap' => '59100'],
        ['codice' => 34,  'nome' => 'RAGUSA',               'cap' => '97100'],
        ['codice' => 23,  'nome' => 'RAVENNA',              'cap' => '48123'],
        ['codice' => 17,  'nome' => 'REGGIO CALABRIA',      'cap' => '89018'],
        ['codice' => 19,  'nome' => 'REGGIO EMILIA',        'cap' => '42124'],
        ['codice' => 174, 'nome' => 'RIVOLI',               'cap' => '10098'],
        ['codice' => 123, 'nome' => 'ROMA AURELIO',         'cap' => '00163'],
        ['codice' => 109, 'nome' => 'ROMA CASILINO',        'cap' => '00133'],
        ['codice' => 124, 'nome' => 'ROMA CENTRO',          'cap' => '00155'],
        ['codice' => 72,  'nome' => 'ROMA FIANO 2',         'cap' => '00065'],
        ['codice' => 103, 'nome' => 'ROMA FIUMICINO',       'cap' => '00065'],
        ['codice' => 255, 'nome' => 'ROMA LA RUSTICA',      'cap' => '00155'],
        ['codice' => 187, 'nome' => 'ROMA TIBURTINA',       'cap' => '00012'],
        ['codice' => 141, 'nome' => 'ROVATO',               'cap' => '25038'],
        ['codice' => 172, 'nome' => 'ROVERETO',             'cap' => '38068'],
        ['codice' => 64,  'nome' => 'ROVIGO',               'cap' => '45100'],
        ['codice' => 225, 'nome' => 'ROVIGO MESSAGGERIA',   'cap' => '45100'],
        ['codice' => 78,  'nome' => 'SALERNO',              'cap' => '84090'],
        ['codice' => 152, 'nome' => 'SALZANO',              'cap' => '30030'],
        ['codice' => 3,   'nome' => 'SAVONA',               'cap' => '17047'],
        ['codice' => 41,  'nome' => 'SCHIO',                'cap' => '36015'],
        ['codice' => 175, 'nome' => 'SEDRIANO 2',           'cap' => '20018'],
        ['codice' => 120, 'nome' => 'SEGRATE',              'cap' => '20054'],
        ['codice' => 178, 'nome' => 'SETTIMO TORINESE',     'cap' => '10036'],
        ['codice' => 80,  'nome' => 'SIENA',                'cap' => '53035'],
        ['codice' => 33,  'nome' => 'SIRACUSA',             'cap' => '96100'],
        ['codice' => 97,  'nome' => 'SONDRIO',              'cap' => '23010'],
        ['codice' => 228, 'nome' => 'STEZZANO',             'cap' => '24040'],
        ['codice' => 10,  'nome' => 'TARANTO',              'cap' => '74123'],
        ['codice' => 151, 'nome' => 'TERAMO',               'cap' => '64023'],
        ['codice' => 155, 'nome' => 'TERMOLI',              'cap' => '66050'],
        ['codice' => 27,  'nome' => 'TERNI',                'cap' => '05035'],
        ['codice' => 49,  'nome' => 'TORINO ORBASSANO',     'cap' => '10040'],
        ['codice' => 115, 'nome' => 'TORINO PESCARITO',     'cap' => '10099'],
        ['codice' => 119, 'nome' => 'TORINO SUD',           'cap' => '10043'],
        ['codice' => 42,  'nome' => 'TRANI',                'cap' => '76125'],
        ['codice' => 47,  'nome' => 'TRENTO',               'cap' => '38121'],
        ['codice' => 59,  'nome' => 'TREVISO',              'cap' => '31032'],
        ['codice' => 170, 'nome' => 'TRIESTE AURISINA',     'cap' => '34011'],
        ['codice' => 95,  'nome' => 'UDINE',                'cap' => '33010'],
        ['codice' => 87,  'nome' => 'VARESE GEMONIO',       'cap' => '21036'],
        ['codice' => 98,  'nome' => 'VENEZIA',              'cap' => '30173'],
        ['codice' => 12,  'nome' => 'VERCELLI',             'cap' => '13012'],
        ['codice' => 169, 'nome' => 'VERONA BUSSOLENGO',    'cap' => '37012'],
        ['codice' => 189, 'nome' => 'VERONA NORD',          'cap' => '37012'],
        ['codice' => 43,  'nome' => 'VERONA S.G. LUPATOTO', 'cap' => '37057'],
        ['codice' => 126, 'nome' => 'VERONA ZAI',           'cap' => '37136'],
        ['codice' => 157, 'nome' => 'VIBO VALENTIA',        'cap' => '89900'],
        ['codice' => 60,  'nome' => 'VICENZA',              'cap' => '36100'],
        ['codice' => 133, 'nome' => 'VILLORBA',             'cap' => '31020'],
        ['codice' => 71,  'nome' => 'VITERBO',              'cap' => '01100'],
    ],
];
